/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ntc;

import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell 7010
 */
public final class MainDesk extends javax.swing.JFrame {

    /**
     * Creates new form MainDesk
     */
    public MainDesk() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        checkPermissions();    
        
    }
    
    public void checkPermissions(){
        if(!login.permissions.equals("admin")){
            customers.hide();           
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        users = new javax.swing.JMenu();
        customers = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        sales = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Naeem Trading Company Faisalabad Branch \t\tFiaz Ul Haq ( 03006665078 )");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        users.setText("User");
        users.setFocusable(false);
        users.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jMenuBar1.add(users);

        customers.setText("Customers");
        customers.setFocusable(false);
        customers.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N

        jMenuItem1.setText("New Customer     ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        customers.add(jMenuItem1);

        jMenuBar1.add(customers);

        sales.setText("Sales");
        sales.setFocusable(false);
        sales.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N

        jMenuItem2.setText("Counter Sale     ");
        jMenuItem2.setMinimumSize(new java.awt.Dimension(780, 680));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        sales.add(jMenuItem2);

        jMenuBar1.add(sales);

        jMenu8.setText("Employees");
        jMenu8.setFocusable(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N

        jMenuItem7.setText("New Employee     ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuBar1.add(jMenu8);

        jMenu7.setText("About Us");
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new NewCustomer(this,true,"").show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//         TODO add your handling code here:
        try {
            CounterSale obj=new CounterSale(this);
            jDesktopPane1.add(obj);
            obj.show();
            obj.setLocation((int)(jDesktopPane1.getWidth()-obj.getWidth())/2,(int)(jDesktopPane1.getHeight()-obj.getHeight())/2);
            obj.setSelected(true);
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
//        try {
//            NewEmployee obj=new NewEmployee();
//            jDesktopPane1.add(obj);
//            obj.show();
//            obj.setLocation((int)(jDesktopPane1.getWidth()-obj.getWidth())/2,(int)(jDesktopPane1.getHeight()-obj.getHeight())/2);
//            obj.setSelected(true);
//        } catch (PropertyVetoException e) {
//            JOptionPane.showMessageDialog(rootPane, e.getMessage());
//        }   
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDesk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu customers;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu sales;
    private javax.swing.JMenu users;
    // End of variables declaration//GEN-END:variables
}
