/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ntc;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Dell 7010
 */
public class NewCustomer extends javax.swing.JDialog {

    private final Action action;
    public NewCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.action = new AbstractAction("customerSave") {
            @Override public void actionPerformed(ActionEvent e) {
                if (!name.getText().equals("")) {
                    mesg.setText("Error :");
                    if (cell.getText().length() == 11) {
                        mesg.setText("Error :");
                        saveCustomer();
                    } else {
                        mesg.setText("Error : Enter Valid Customer Cell No.");
                        cell.grabFocus();
                    }
                } else {
                    mesg.setText("Error : Enter Customer Name");
                    name.grabFocus();
                }
            }
        };
        initComponents();
        getRootPane().getInputMap().put(KeyStroke.getKeyStroke("F9"), action);
        setLocationRelativeTo(null);
    }
    public NewCustomer(java.awt.Frame parent, boolean modal,String cellNo){
        super(parent, modal);
        this.action = new AbstractAction("customerSave") {
            @Override public void actionPerformed(ActionEvent e) {
                if (!name.getText().equals("")) {
                    mesg.setText("Error :");
                    if (cell.getText().length() == 11) {
                        mesg.setText("Error :");
                        saveCustomer();
                    } else {
                        mesg.setText("Error : Enter Valid Customer Cell No.");
                        cell.grabFocus();
                    }
                } else {
                    mesg.setText("Error : Enter Customer Name");
                    name.grabFocus();
                }
            }
        };
        initComponents();
        getRootPane().registerKeyboardAction(action, KeyStroke.getKeyStroke("F9"), JComponent.WHEN_IN_FOCUSED_WINDOW);
        setLocationRelativeTo(null);
        cell.setText(cellNo);
    }
/**
     * Creates new form customer
     * @param parent
     * @param modal
     */
        public void saveCustomer(){
        try(Connection con=db.getConnection()){
            PreparedStatement ps = con.prepareStatement("insert into customers("
                    + "cust_name,"
                    + "cell_no,"
                    + "phone,"
                    + "address,"
                    + "active,"
                    + "remarks ) values(?,?,?,?,?,?)");
            ps.setString(1, name.getText());
            ps.setString(2, cell.getText());
            ps.setString(3, phone.getText());
            ps.setString(4, address.getText());
            ps.setString(5, active.isSelected()==true?"YES" :"NO");
            ps.setString(6, remarks.getText());            
            if(ps.executeUpdate()==1){
//                JOptionPane.showMessageDialog(rootPane, "Customer Saved");
                hide();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error While Saving New Customer \nCall Your vander");
                hide();
            }            
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            System.exit(-1);
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        active = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        mesg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        remarks = new javax.swing.JTextField();
        cell = new javax.swing.JFormattedTextField(Utils.formatCellNumber());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW CUSTOMER");
        setResizable(false);

        jLabel2.setText("Customer Name");

        jLabel3.setText("Cell #");

        jLabel4.setText("Phone No.");

        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        address.setColumns(20);
        address.setRows(5);
        address.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jScrollPane1.setViewportView(address);

        active.setSelected(true);
        active.setText("Active");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mesg.setForeground(new java.awt.Color(255, 0, 0));
        mesg.setText("Error :");

        jLabel1.setText("Remarks");

        remarks.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remarks)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(active)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addComponent(cell))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mesg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(active))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(mesg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!name.getText().equals("")){
            mesg.setText("Error :");
            if(cell.getText().length()==11){
                mesg.setText("Error :");
                saveCustomer();
            }else{
                mesg.setText("Error : Enter Valid Customer Cell No.");
                cell.grabFocus();
            }
        }else{
            mesg.setText("Error : Enter Customer Name");
            name.grabFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox active;
    private javax.swing.JTextArea address;
    private javax.swing.JFormattedTextField cell;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesg;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField remarks;
    // End of variables declaration//GEN-END:variables
}
