/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ntc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Umar Rehman
 */
public class SaleInvoiceDetail extends javax.swing.JDialog {

    /**
     * Creates new form SaleInvoiceDetail
     */
    private StringTokenizer skuTokenizer, qtyTokenizer, ratesTokenizer;
    private final DefaultTableModel model;
    private final JFrame parent;

    public SaleInvoiceDetail(long invoiceNo,JFrame parent) {
        super(parent,false);
        initComponents();
        this.parent=parent;
        setLocationRelativeTo(null);
        model = (DefaultTableModel) jXTable1.getModel();
        getInvoiceDetails(invoiceNo);
    }

    private void getInvoiceDetails(long invoice) {
        try (Connection con = db.getConnection()) {
            PreparedStatement ps = con.prepareStatement("select skus,qty,rates from invoices_details where fk_invoice=?");
            ps.setLong(1, invoice);
            ResultSet res = ps.executeQuery();
            while (res.next()) {
                skuTokenizer = new StringTokenizer(res.getString(1), ",");
                qtyTokenizer = new StringTokenizer(res.getString(2), ",");
                ratesTokenizer = new StringTokenizer(res.getString(3), ",");
                int counter = 1;
                while (skuTokenizer.hasMoreElements()) {
                    String str = skuTokenizer.nextToken();
                    int qty = Integer.parseInt(qtyTokenizer.nextToken());
                    float rates = Float.parseFloat(ratesTokenizer.nextToken());
                    ps = con.prepareStatement("select description from products where sku=?");
                    ps.setInt(1, Integer.parseInt(str));
                    res = ps.executeQuery();
                    if (res.next()) {
                        model.addRow(new Object[]{counter++, res.getString(1), qty, rates,qty*rates});
                    } else {
                        System.out.println("No Records ");
                    }
                }
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        setTitle("Invoice Details");
        setResizable(false);

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Product Name", "Quantity", "Rate", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.setRowHeight(25);
        jXTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jXTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
